<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbe5e92daf705d06dc5d0ff5ac5f906fb
{
    public static $prefixLengthsPsr4 = array (
        'U' => 
        array (
            'Usuario\\BarcodeGenerator\\' => 25,
        ),
        'P' => 
        array (
            'Picqer\\Barcode\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Usuario\\BarcodeGenerator\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'Picqer\\Barcode\\' => 
        array (
            0 => __DIR__ . '/..' . '/picqer/php-barcode-generator/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbe5e92daf705d06dc5d0ff5ac5f906fb::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbe5e92daf705d06dc5d0ff5ac5f906fb::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitbe5e92daf705d06dc5d0ff5ac5f906fb::$classMap;

        }, null, ClassLoader::class);
    }
}
